build:
  stage: build
  script:
    - echo "Build stage"
    - yarn build
  artifacts:
    paths:
      - dist
    expire_in: 1 hour
test:
  stage: test
  script:
    - echo "Test stage"
deploy:
  stage: deploy
  script:
    - echo "Deploy stage"
