version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    ports:
      - 4200:80
    environment:
      - NX_API_SCHEME_HTTP=https
      - NX_API_SCHEME_WS=wss
      - NX_API_HOST=127.0.0.1
      - NX_API_PORT=4300
      - NX_API_ENDPOINT=graphql

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    ports:
      - 4300:4300
