version: '3.8'

services:
  client:
    depends_on:
      - server
    networks:
      - rally_network

  server:
    depends_on:
      database:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - rally_network

  migrate:
    depends_on:
      database:
        condition: service_healthy
    networks:
      - rally_network

  database:
    image: postgres:17.5-alpine
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready --user chat_user -d chat']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '6543:5432'
    environment:
      - POSTGRES_DB=chat
      - POSTGRES_USER=chat_user
      - POSTGRES_PASSWORD=salainen
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
    networks:
      - rally_network

networks:
  rally_network:
    name: rally_network
