version: '3.8'

services:
  client:
    container_name: websocket-chat_client
    image: websocket-chat_base
    ports:
      - 4200:4200
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps:/usr/src/apps
      - ./libs:/usr/src/libs
    command: yarn nx serve client --host 0.0.0.0
  server:
    container_name: websocket-chat_server
    image: websocket-chat_base
    environment:
      - NODE_ENV=development
    ports:
      - 4300:4300
    volumes:
      - ./apps:/usr/src/apps
      - ./libs:/usr/src/libs
    depends_on:
      - database
    command: yarn nx serve server
  database:
    container_name: websocket-chat_database
    image: postgres:13.3-alpine
    ports:
      - '6543:5432'
    env_file:
      - ./apps/migration/.env
  database_migration:
    container_name: websocket-chat_database_migration
    image: websocket-chat_base
    command:
      [
        './shell/wait-for-it.sh',
        'database:5432',
        '--',
        'yarn',
        'knex',
        'migrate:latest',
      ]
    env_file:
      - ./apps/migration/.env
    environment:
      # Overwrite environment variables
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      # wait-for-it environment variables
      - WAITFORIT_TIMEOUT=5 # Defaul 15
      #- WAITFORIT_STRICT # Default 0
      #- WAITFORIT_CHILD # Default 0
      #- WAITFORIT_QUIET # Default 0
    depends_on:
      - database
