version: '3.8'

services:
  chat-client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    networks:
      - chat_network

  chat-server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    ports:
      - 4300:4300
    environment:
      - PORT=4300
      - JWT_SECRET=SALAINEN
      - POSTGRES_DB=chat
      - POSTGRES_USER=chat_user
      - POSTGRES_PASSWORD=salainen
      - POSTGRES_HOST=chat-database
      - POSTGRES_PORT=5432
    networks:
      - chat_network
