version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    ports:
      - 4200:80
    environment:
      - PORT=80
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    ports:
      - 4300:4300
