# ------------------------------------------------------
# NGINX proxy
# ------------------------------------------------------
FROM nginx:1.25.2-alpine

RUN apk --no-cache --update add dumb-init vim

COPY nginx.prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 80/tcp
EXPOSE 443/tcp

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["sh", "-c", "nginx -g 'daemon off;'"]