# Requires to have base image built:
# docker build -f Dockerfile -t rally-base .
version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile.local
      args:
        VITE_NX_API_SCHEME_HTTP: http
        VITE_NX_API_SCHEME_WS: ws
        VITE_NX_API_HOST: localhost
        VITE_NX_API_HOST_SSR: server
        VITE_NX_API_PORT: 5300
        VITE_NX_API_ENDPOINT: graphql
    ports:
      - 5200:5200
    environment:
      - PORT=5200

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile.local
    ports:
      - 5300:5300
    environment:
      - PORT=5300
      - JWT_SECRET=SALAINEN
      - POSTGRES_HOST=database
      - POSTGRES_USER=chat_user
      - POSTGRES_DB=chat
      - POSTGRES_PASSWORD=salainen
      - POSTGRES_PORT=5432

  migrate:
    build:
      context: .
      dockerfile: ./apps/migrate/Dockerfile.local
    environment:
      - DATABASE_URL=postgresql://chat_user:salainen@database:5432/chat
      - ROLE=member

  database:
    image: postgres:17.5-alpine
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready --user chat_user -d chat']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '6543:5432'
    environment:
      - POSTGRES_DB=chat
      - POSTGRES_USER=chat_user
      - POSTGRES_PASSWORD=salainen
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
    networks:
      - rally_network

networks:
  rally_network:
    name: rally_network
