// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.channel */
export type ChannelId = string & { __brand: 'ChannelId' };

/** Represents the table public.channel */
export default interface Channel {
  id: ChannelId;

  createdAt: Date | null;

  updatedAt: Date | null;
}

/** Represents the initializer for the table public.channel */
export interface ChannelInitializer {
  /** Default value: uuid_generate_v4() */
  id?: ChannelId;

  /** Default value: CURRENT_TIMESTAMP */
  createdat?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updatedat?: Date | null;
}

/** Represents the mutator for the table public.channel */
export interface ChannelMutator {
  id?: ChannelId;

  createdat?: Date | null;

  updatedat?: Date | null;
}
