// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the compositeType public.jwt_token */
export default interface JwtToken {
  role: string | null;

  memberId: string | null;

  exp: string | null;
}
