// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.member */
export type MemberId = string & { __brand: 'MemberId' };

/** Represents the table public.member */
export default interface Member {
  id: MemberId;

  firstName: string;

  lastName: string;

  createdAt: Date | null;

  updatedAt: Date | null;
}

/** Represents the initializer for the table public.member */
export interface MemberInitializer {
  /** Default value: uuid_generate_v4() */
  id?: MemberId;

  firstname: string;

  lastname: string;

  /** Default value: CURRENT_TIMESTAMP */
  createdat?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updatedat?: Date | null;
}

/** Represents the mutator for the table public.member */
export interface MemberMutator {
  id?: MemberId;

  firstname?: string;

  lastname?: string;

  createdat?: Date | null;

  updatedat?: Date | null;
}
