// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { MemberId } from './Member';

/** Represents the table public.member_account */
export default interface MemberAccount {
  memberId: MemberId;

  email: string;

  passwordHash: string;
}

/** Represents the initializer for the table public.member_account */
export interface MemberAccountInitializer {
  memberid: MemberId;

  email: string;

  passwordhash: string;
}

/** Represents the mutator for the table public.member_account */
export interface MemberAccountMutator {
  memberid?: MemberId;

  email?: string;

  passwordhash?: string;
}
