// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { MemberId } from './Member';
import type { ChannelId } from './Channel';

/** Identifier type for public.message */
export type MessageId = string & { __brand: 'MessageId' };

/** Represents the table public.message */
export default interface Message {
  id: MessageId;

  memberId: MemberId | null;

  channelId: ChannelId | null;

  text: string;

  createdAt: Date | null;

  updatedAt: Date | null;
}

/** Represents the initializer for the table public.message */
export interface MessageInitializer {
  /** Default value: uuid_generate_v4() */
  id?: MessageId;

  memberid?: MemberId | null;

  channelid?: ChannelId | null;

  text: string;

  /** Default value: CURRENT_TIMESTAMP */
  createdat?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updatedat?: Date | null;
}

/** Represents the mutator for the table public.message */
export interface MessageMutator {
  id?: MessageId;

  memberid?: MemberId | null;

  channelid?: ChannelId | null;

  text?: string;

  createdat?: Date | null;

  updatedat?: Date | null;
}
