// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.channel */
export type ChannelId = string & { __brand: 'public.channel' };

/** Represents the table public.channel */
export default interface Channel {
  id: ChannelId;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.channel */
export interface ChannelInitializer {
  /** Default value: uuid_generate_v4() */
  id?: ChannelId;

  /** Default value: now() */
  createdat?: Date;

  /** Default value: now() */
  updatedat?: Date;
}

/** Represents the mutator for the table public.channel */
export interface ChannelMutator {
  id?: ChannelId;

  createdat?: Date;

  updatedat?: Date;
}
