// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface current_member_id_params {
}

/** Return type for current_member_id */
export type current_member_id_return_type = string;
