// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface invalidate_session_params {
  p_token: string;
}

/** Return type for invalidate_session */
export type invalidate_session_return_type = boolean;
