// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { MemberId } from './Member';

/** Identifier type for public.member_session */
export type MemberSessionToken = string & { __brand: 'public.member_session' };

/** Represents the table public.member_session */
export default interface MemberSession {
  memberId: MemberId;

  token: MemberSessionToken;

  invalidated: boolean | null;

  createdAt: Date;

  expiresAt: Date;

  lastUsedAt: Date;
}

/** Represents the initializer for the table public.member_session */
export interface MemberSessionInitializer {
  memberid: MemberId;

  token: MemberSessionToken;

  /** Default value: false */
  invalidated?: boolean | null;

  /** Default value: now() */
  createdat?: Date;

  expiresat: Date;

  /** Default value: now() */
  lastusedat?: Date;
}

/** Represents the mutator for the table public.member_session */
export interface MemberSessionMutator {
  memberid?: MemberId;

  token?: MemberSessionToken;

  invalidated?: boolean | null;

  createdat?: Date;

  expiresat?: Date;

  lastusedat?: Date;
}
