// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { MemberId } from './Member';
import type { ChannelId } from './Channel';

/** Identifier type for public.message */
export type MessageId = string & { __brand: 'public.message' };

/** Represents the table public.message */
export default interface Message {
  id: MessageId;

  memberId: MemberId;

  channelId: ChannelId;

  text: string;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.message */
export interface MessageInitializer {
  /** Default value: uuid_generate_v4() */
  id?: MessageId;

  memberid: MemberId;

  channelid: ChannelId;

  text: string;

  /** Default value: now() */
  createdat?: Date;

  /** Default value: now() */
  updatedat?: Date;
}

/** Represents the mutator for the table public.message */
export interface MessageMutator {
  id?: MessageId;

  memberid?: MemberId;

  channelid?: ChannelId;

  text?: string;

  createdat?: Date;

  updatedat?: Date;
}
