// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.pg_migrations */
export type PgMigrationsId = number & { __brand: 'public.pg_migrations' };

/** Represents the table public.pg_migrations */
export default interface PgMigrations {
  id: PgMigrationsId;

  name: string;

  runOn: Date;
}

/** Represents the initializer for the table public.pg_migrations */
export interface PgMigrationsInitializer {
  /** Default value: nextval('pg_migrations_id_seq'::regclass) */
  id?: PgMigrationsId;

  name: string;

  runon: Date;
}

/** Represents the mutator for the table public.pg_migrations */
export interface PgMigrationsMutator {
  id?: PgMigrationsId;

  name?: string;

  runon?: Date;
}
