// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface register_member_params {
  first_name: string;

  last_name: string;

  email: string;

  password: string;
}
