// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface verify_authentication_params {
  p_token: string;
}

/** Return type for verify_authentication */
export type verify_authentication_return_type = boolean;
